language: node_js
node_js:
   - '0.10'
before_script:
   - 'npm install -g gulp'
   - 'npm install -g bower'
   - 'bower install'
before_install:
   - './.travis/scripts/install_chrome.sh'
   - 'export DISPLAY=:99.0'
   - 'sh -e /etc/init.d/xvfb start'